### ISSUE TITLE
Benefits of returning a specific error message when ParseIDs fails?

### ISSUE THREAD

**Issue by datafoo** [absinthe-graphql/absinthe_relay#143]
When the conversion from a global ID to a node’s type name and ID fails, I noticed that a specific error message is returned. It is nice to understand why it fails, in development.

Example of specific error messages:
- In argument \"input\": In field \"userId\": Could not extract value from decoded ID `\":2\"`
- In argument \"input\": In field \"userId\": Could not decode ID value `user#123'
- In argument \"input\": In field \"userId\": Unknown type `Foo'
- In argument \"input\": In field \"userId\": Expected node type in [\"User\"], found \"Bar\"

However, the way I understand global ID is that it is an opaque value (whether it is base64-encoded or not). Please tell me if that assumption is wrong.

So, in production, how relevant is it to return such specific error message which reveals the implementation details of how global IDs are build?

Would not that make sense to return a generic error message instead? At least in production?

**Comment by benwilson512** [comment]
Useful errors is even more important in production than in development because developers have much less context in production than in development. If your error aggregation tool gives you a bunch of "invalid id" messages from production, you don't have a ton to go on. If you get specific error messages it's a lot more helpful.

None of this violates the opaqueness principle. Opaqueness isn't about the contents of the ID being secret, they're only base64 encoded afterall. Opaqueness is about the client not trying decipher the meaning of the id, or use some internal property of it for its own purposes. When you get these errors back these are errors from the server, not the client.

**Comment by datafoo** [comment]
Global IDs are generated by the server. Clients are not supposed to decipher, tamper or forge such IDs. So clients can only pass them back to the server as is.

In these conditions, what are the use cases where a server response with a message more specific than "invalid id" can be useful?

Sorry if I don't see the obvious.

**Comment by benwilson512** [comment]
Consider the mutation:
```
mutation ($id: ID!) {
  updateUser(id: $id, name: "foo") { ...Whatever }
}
```

Suppose further the API supports ` { products { id name } }` and that the front end code has a bug such that it is passing an `id` it retrieved from the `products` query to the `updateUser` mutation.

Error messages as they exist today are extremely useful for detecting this kind of bug, because the server will inform the client that the `id` being passed in is the wrong kind of `id`. None of that requires that the client do any of "decipher, tamper or forge" with respect to IDs.

**Comment by datafoo** [comment]
This bug would also be "detected" with a generic error message but the cause would indeed be easier to find with the specific message.
I understand better now. Thank you.
