### ISSUE TITLE
Overriding cursor throws warning

### ISSUE THREAD

**Issue by AtithAlur** [absinthe-graphql/absinthe_relay#152]
As per the documentation - https://hexdocs.pm/absinthe_relay/Absinthe.Relay.Connection.html
If we provide a `:cursor` argument then the value should override the internally generated cursor.
But, It's throwing a warning: `[warn] Ignoring additional cursor provided on edge (overriding is not allowed)`
And the warning is as per the code: https://github.com/absinthe-graphql/absinthe_relay/blob/643a9c42f7f3d0e4253468aef76563287d7ee0ee/lib/absinthe/relay/connection.ex#L582

Is this an outdated document or am I doing it wrong?

**Comment by panmichal** [comment]
Looks like the possibility of overriding the default cursor was removed after a discussion: https://github.com/absinthe-graphql/absinthe_relay/pull/109#issuecomment-397938674

So perhaps outdated module doc.

**Comment by ronaldcurtis** [comment]
I think there are some strong arguments for why we should have the ability to override cursors. Here is why:

1. We could be interfacing with external services that use their own cursors. (This issue has already been raised at https://github.com/absinthe-graphql/absinthe_relay/issues/161)
2. Currently the `cursors` in this package just encode the `OFFSET` and `OFFSET + LIMIT`. But we may not want to use `OFFSET` in our SQL queries because it results in [slow performance](https://use-the-index-luke.com/sql/partial-results/fetch-next-page).

I personally have a project involving both of the above issues. Is there a current workaround for overriding cursors?
