### ISSUE TITLE
Extend automatic global/internal id mapping to mutation input fields

### ISSUE THREAD

**Issue by skosch** [absinthe-graphql/absinthe_relay#16]
An oft-repeated pattern in my code:

```elixir
input do
  field :id, :string  # global id for the :item
end
```

followed in the resolver by something like

```elixir
def find(%{id: item_global_id}, _info) do
  {:ok, %{id: id}} = Absinthe.Relay.Node.from_global_id(item_global_id, App.Schema)
...
```

It would be great if we could instead define
```
input do:
  field :id, global_id(:item)
end
```
... and get access to the whole `item` in the resolver, including its internal id. (Or maybe just a `:global_id` type that gets mapped onto an internal id, and the user can choose to pull the `item`'s data if necessary.)

**Comment by bruce** [comment]
So I don't think this belongs as a wrapper around the type itself -- for a number of implementation reasons.

A few options:

- We use a macro pattern like we use elsewhere, and have something like `global_id field :id, :item` (this will take a bit to work out, as it amounts to registering a change we need to apply all together before we call your resolver)
- As a workaround in our own code, we use a higher order function with the resolver -- since this is really a issue with what arguments are passed to the schema designer's resolver function.

For example, this wraps your resolver (returned from `Resolver.lookup/1`) with another function that converts node IDs for you, making sure they match the right type:

`resolve Resolver.lookup(:mutation_foo) |> node_id(id: :item)`

Here's our `node_id`:

```elixir
  def node_id(fun, id_keys) do
    fn args, info ->
      args = Enum.reduce(id_keys, args, fn {key, type}, args ->
        with {:ok, global_id} <- Map.fetch(args, key),
             {:ok, %{id: id, type: ^type}} <- Absinthe.Relay.Node.from_global_id(global_id, Your.Schema) do
          {:success, Map.put(args, key, id)}
        end
        |> case do
          {:ok, %{type: bad_type}} ->
            raise ArgumentError, """
            Should have parsed as type: #{inspect type}.
            Instead got: #{inspect bad_type}
            """
          {:success, args} -> args
          _ -> args
        end
      end)

      fun.(args, info)
    end
  end
```

Personally, I like the idea of making this more about the resolver than the field definition -- it's already rather tricky figuring out which macro to use between nodes, connections, and mutations.

@benwilson512 Have any thoughts?

**Comment by skosch** [comment]
Whoa, cool. That's certainly an option I would consider. I wonder if that wrapper could be provided by the library?

**Comment by bruce** [comment]
Yeah, I think so. I think I'd opt for a name like `parsing_node_id`.

**Comment by bruce** [comment]
@skosch Can you give PR #17 a look, see how that works for you?

**Comment by skosch** [comment]
Seems to work for me so far. You guys rock. (Now it's just a matter of documenting it.)
