### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by anthonator** [absinthe-graphql/absinthe_relay#195]
Would it be possible to get a new release? #194 fixes Ci issues in `master`.

**Comment by kdawgwilk** [comment]
there are a few changes in master that are not released that would be nice to get https://github.com/absinthe-graphql/absinthe_relay/compare/v1.5.1...master including loosening up the absinthe version requirements to allow absinthe 1.7.0

**Comment by jtomaszewski** [comment]
Just checked commit log. The only changes that need documenting in the new release are:

- https://github.com/absinthe-graphql/absinthe_relay/commit/8d20d548e80d263f647087020f0dbde5499ffcc3
- https://github.com/absinthe-graphql/absinthe_relay/pull/193

all the other commits that went since the last release (1.5.1) are just CI/docs changes.

@benwilson512 , could we ask for your 5 minutes on this? 🙏

**Comment by benwilson512** [comment]
Done.
