### ISSUE TITLE
Return all edges in connection (Connection.from_list/3)

### ISSUE THREAD

**Issue by hisapy** [absinthe-graphql/absinthe_relay#31]
Currently, when you call Connection.from_list without pagination args, it fails with the error

```shell
** (exit) an exception was raised:
    ** (CaseClauseError) no case clause matching: 0
        lib/absinthe/relay/connection.ex:215: Absinthe.Relay.Connection.from_list/3
....
````
You can reproduce the error with a query like the following.

```graphql
query{
  node(id: "RmFjdGlvbjoy") {
    id
    ... on Faction{
      name
      ships {
        edges {
          node {
            id
          }
        }
      }
    }
  }
}
```

However everything works if you pass pagination args as in:

```graphql
query{
  node(id: "RmFjdGlvbjoy") {
    id
    ... on Faction{
      name
      ships(first: 10) {
        edges {
          node {
            id
          }
        }
      }
    }
  }
}
```

Do you think we can change the behaviour of the `Connection.from_list` to return all edges in the connection if no pagination args are specified ?

**Comment by sjchmiela** [comment]
No, we (or “they” for that matter) cannot, because it would violate [GraphQL Connection Spec](https://facebook.github.io/relay/graphql/connections.htm#sec-Arguments), stating that:

> A field that returns a Connection Type **must** include forward pagination arguments, backward pagination arguments, or both.

…and the `ships` field returns a Connection Type.

An alternative would be to leave the Connection Type and just return a `list_of(:ship)` without arguments or to specify both (`shipsConnection` and `ships`).

**Comment by hisapy** [comment]
Ok thanks for the explanation @sjchmiela ... It makes sense ... I think it'll be ok to close this issue then, unless there's another opinion out there.

**Comment by hudon** [comment]
FWIW, I believe this is just one interpretation of that part of the spec... another way to read it is that the connection type must support either forward pagination or backwards or both so that the client has a way of requesting pagination, but the client is not forced to request pagination. The client can omit the pagination arguments and get the whole collection.
In fact, this is how https://github.com/rmosolgo/graphql-ruby interpreted the spec (ie. server must allow pagination requests, but not force clients to request pagination).
