### ISSUE TITLE
`clientMutationId` as an optional feature?

### ISSUE THREAD

**Issue by avitex** [absinthe-graphql/absinthe_relay#55]
From what I can see, apollo-client does not require `clientMutationId`, making it a pretty redundant field.
A potential fix for this would be to provide, in the initial absinthe config, a switch to disable it for the clients that don't need it.

I'm happy to craft a PR after discussion. Any thoughts?

**Comment by benwilson512** [comment]
This is something of a difficult question. On the one hand, many people using apollo do still use some of the conventions from relay, and thus this library to assist with that. On the other hand, I am inclined to think that trying to make this library support BOTH whatever conventions Relay comes up with as well as Apollo is likely to make it bad at both.

Trying to make a separate Absinthe.Apollo library is sensible, but will also likely result in a lot of duplicate code between them. I'm not entirely sure what the best route forward is.

**Comment by bruce** [comment]
My opinion: this package is here to support Relay's quirks, and should enforce Relay's constraints. Apollo doesn't really have constraints (at this point) or strongly conventional practices for, eg, mutations (at least that I've seen) that would warrant a separate "official" Absinthe package.

If someone wants a _close to_ absinthe_relay mechanism for building mutations, pulling out the associated module, modifying the macros as needed, and using it in their project is pretty straightforward. People could even publish their own packages -- that's something we'd really _love_ to see done, if there are patterns and best practices that people think are worth putting out there.

Absinthe's "official" client-supporting packages, though, should remain narrowly-defined and specific.

**Comment by tlvenn** [comment]
>My opinion: this package is here to support Relay's quirks, and should enforce Relay's constraints. 

Ya I agree with @bruce but I understand the dilemna of having a separate Absinthe.Apollo lib with the code duplication it will create. Would it be possible to push the common area into one helper lib that Absinthe.Relay and Absinthe.Apollo would use to compose their own helpers ?

If this is of any help, i have a fork of absinthe_relay without clientMutationId and optional input as well which is a side effect of not enforcing the clientMutationId:
>https://github.com/jumpn/absinthe_relay

I could clean it up by removing relay specific stuff and rename the repo if needed / desired.

**Comment by tlvenn** [comment]
I have updated my fork to the latest on master and cherry picked my 2 commits

**Comment by bruce** [comment]
Some background here, for those interested -- it probably makes sense to capture a bit of what I've been thinking with regard to schema features/patterns that go beyond the specification and framework constraints, and how I think Absinthe (as a project) should look at them.  (@benwilson512 may disagree with me; these are just my words, and I apologize up front for my verbosity.)

The thing that drives our decision to make client-specific packages (as part of the larger Absinthe project) so far have been constraints that the client frameworks require (and that are a pain to do manually). Thus far, Apollo has given us no reason to create an absinthe_apollo -- although I'd be very interested in us doing so if Apollo started being more prescriptive.

What I don't want to get into the habit of us doing "officially" is deciding on best practices within Relay/Apollo that we push on Absinthe schema designers (as an example, it even took some time for me to come around to the idea of having custom types in the Absinthe package itself). Part of this, for me, is ethical (who am I to decide?), part of it is practical (it can be a lot of work to maintain code and defend those decisions), and part of it is a desire to encourage a community and ecosystem to be built around Absinthe -- from without -- to make it more robust, more inclusive, and appeal to a wider audience. For these reasons, my default response to people coming up with patterns -- even when I think the patterns are _right_, their authors creative geniuses, and I plan on using them myself -- will be to request the package be published independently. This isn't to say we won't recommend the package in guides, in Slack, in talks, etc. Maybe someday we'll even discuss with the author about making it an "official" package and pulling it into the absinthe-graphql GitHub organization. (For the moment Absinthe is a bit young to be getting into any long-term relationships.)

Back to this specific case, my thoughts:
- If a generic payload-style mutation pattern is something people want (something I completely understand), by all means, please do publish a package. I'd caution against labeling it "apollo," as, once again, there's nothing Apollo-specific about it, and there are other, lighter clients.
- For the moment, I'd recommend copying (code duplication). I don't recommend this necessarily because I don't want to create a helper library out of laziness, but because a significant amount of flux is going to be happen in the low-level Absinthe machinery that's used to build schemas (eg, macros will modify a Blueprint node tree that represents a schema, and that tree will undergo a customizable pipeline transformation, just like requests... but with the end result being a compiled schema). Because this is my post-ElixirConf EU priority, I don't want to add any additional projects whose internals we need to refactor around the changes, slowing down our release cycle.

Note: I **really** don't want this to sound like I'm dismissing these types of ideas -- quite the opposite, in fact; they deserve maintainers that can give them the attention, thought, and care they deserve. If you'll forgive a very bad naval metaphor: I would be very, very happy to have a whole flotilla of schema types/pattern packages along for support -- Absinthe itself is just a very big ship to steer, and I'm trying to be a prudent sailor.

**Comment by avitex** [comment]
Very valid points @bruce. I thought there would be quite a lot of room for discussion with this particular problem, hence why I didn't make a PR for it initially.

A lot of what absinthe_relay provides is pretty useful outside of the 'react/relay' ecosystem.
Apollo is pretty unopinionated, a clear example of that is pagination with `fetchMore`, though I like the conventions relay provides. I personally use apollo because it's framework agnostic, not tied into react.

I think a lot of `absinthe_relay` could be dragged out into its own package (payload, nodeid helpers, etc), as @tlvenn suggested. However, I don't think this is a high priority at this stage as you mentioned unless someone else wants to start on it. In the long term, I reckon this would be the best path, as it would be very tiresome to maintain multiple packages, much of the same recipe.

And in reply your note, you don't come across at all as dismissive. Absinthe is a wonderful addition to the elixir web ecosystem, and I've been using it pretty much exclusively on multiple projects at home and work. I'm very grateful to you, Ben and all of the other contributors.
