### ISSUE TITLE
has_next_page: Incorrectly returns true when limit is equal to list size

### ISSUE THREAD

**Issue by konradkalita** [absinthe-graphql/absinthe_relay#67]
When you query for connection resource and list result has the same size as limit field `hasNextSize` in `pageInfo`  is true. 

I think this line should be
`has_next_page: args[:first] != nil && length(records) > limit`
https://github.com/absinthe-graphql/absinthe_relay/blob/29349887df8943a8cd73f70f7690d4f45b600003/lib/absinthe/relay/connection.ex#L339

**Comment by kyasu1** [comment]
Hi thank you for the great libs :-)

After this modification, the `has_next_page` never become true, because `length(records)` is always less than or equal to `limit`, as the query indicates. To solve the both problems, probably we need to naively count the total records and compare it with `(offset + limit)` as done in `from_list`.

**Comment by bruce** [comment]
@kyasu1 ugh, yes. We'll take a look at this tomorrow morning. Thanks for pointing this out.

**Comment by benwilson512** [comment]
The downside with doing a count is that we have now to do 2 db queries. My inclination here is to grab `limit + 1` records out of the DB, then use `length(records) > limit`, but then only return `Enum.take(rows, limit)`.

Thoughts?

**Comment by kyasu1** [comment]
@benwilson512 Yea agree with you, less query is always better. I tried your solution in my project and it solved the problem, it is neat. Please take a look at the pull request.
